const initialTasks = [
  {
    id: "1",
    title: "Grocery Shopping",
    category: "3",
    priority: "3",
    dueDate: "2024-05-12",
    assignedTo: ["2"],
    isDone: false,
  },
  {
    id: "2",
    title: "Pay Electricity Bill",
    category: "1",
    priority: "2",
    dueDate: "2024-04-12",
    assignedTo: ["1"],
    isDone: false,
  },
  {
    id: "3",
    title: "Car Maintenance",
    category: "2",
    priority: "1",
    dueDate: "2024-05-12",
    assignedTo: ["1"],
    isDone: false,
  },
  {
    id: "4",
    title: "Parent-Teacher Meeting",
    category: "7",
    priority: "3",
    dueDate: "2024-05-12",
    assignedTo: ["2"],
    isDone: false,
  },
  {
    id: "5",
    title: "Book Club Meeting",
    category: "4",
    priority: "1",
    dueDate: "2024-05-20",
    assignedTo: ["1", "2"],
    isDone: false,
  },
  {
    id: "6",
    title: "Garden Weeding",
    category: "2",
    priority: "2",
    dueDate: "2024-06-18",
    assignedTo: ["2"],
    isDone: false,
  },
  {
    id: "7",
    title: "Vet Appointment for Max",
    category: "6",
    priority: "3",
    dueDate: "2024-05-22",
    assignedTo: ["1", "2"],
    isDone: false,
  },
  {
    id: "8",
    title: "Dentist Appointment",
    category: "5",
    priority: "2",
    dueDate: "2024-06-25",
    assignedTo: ["2"],
    isDone: false,
  },
  {
    id: "9",
    title: "Replace Smoke Detector Batteries",
    category: "2",
    priority: "1",
    dueDate: "2024-05-05",
    assignedTo: ["2"],
    isDone: false,
  },
  {
    id: "10",
    title: "Prepare Guest Room for Visitors",
    category: "4",
    priority: "2",
    dueDate: "2024-05-30",
    assignedTo: ["1", "2"],
    isDone: false,
  },
];

export default initialTasks;
